VERSION="2.2.1"

ACCOUNTS=[
"GBGKEJ2USZZBT7WJFX6MQKRN2QF4UQMHI33KBYPYOGW3TTXL2BDZQZ2I",
]

[DOCUMENTATION]
ORG_NAME="Digital Currency Group"
ORG_URL="https://www.dcg-stellar.com/"
ORG_DESCRIPTION="DCG is the enduring investor & operator of the crypto industry"
ORG_LOGO="https://www.dcg-stellar.com/dcg.png"


[[CURRENCIES]]
code="DCG"
status="live"
display_decimals=2
issuer="GBGKEJ2USZZBT7WJFX6MQKRN2QF4UQMHI33KBYPYOGW3TTXL2BDZQZ2I"
anchor_asset_type="crypto"
name="Digital Currency Group"
desc="DCG is the enduring investor & operator of the crypto industry"
image="https://www.dcg-stellar.com/dcg.png"
fixed_number=1000000
max_number=1000000
is_unlimited=false
#DCG Asset was issued using the open and inclusive Stellar blockchain network.
